version: "3.8"

services:
  flask_app:
    build: .
    container_name: flask_app
    networks:
      - app_network
    ports:
      - "5000:5000"

  openresty:
    image: openresty/openresty:latest
    container_name: openresty
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./access.lua:/app/access.lua
    depends_on:
      - flask_app
      - redis
    networks:
      - app_network
    ports:
      - "8080:80"
  redis:
    image: redis:5.0.14
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network: